### ISSUE TITLE
gib tiny potato

### ISSUE THREAD

**Issue by PhoenixVX** [FukkitMC/Fukkit#4]
or ur bad

**Comment by PhoenixVX** [comment]
i want my tiny potato

**Comment by ramidzkh** [comment]
:arrow_down:
:potato:
:arrow_up:

**Comment by hYdos** [comment]
too bad stolen

**Comment by PhoenixVX** [comment]
Closing issue as off topic. Please re-open this issue if the issue continues.

**Comment by ramidzkh** [comment]
We 👐 are closing 😚 this issue 😭 because 🤔 it currently 🚟🚟 appears 🍆 to be 🐝 off 📴 topic. ➕ However, 💰 if you 😊😀 believe 🌈 the issue 😭 persists or is relevant, kindly 😶🇮🇪☘️ re-open it and provide 👋 further 🔙🤔 details. 🙌🏽 We 👫 appreciate 👌 your 👈 understanding 🌞 and cooperation.

**Comment by PhoenixVX** [comment]
# HELP MY TINY POTATO WAS STOLEN BY HYDOS

**Comment by hYdos** [comment]
no
